// =============================================================================
// ORDEM PARANORMAL RPG — Dados do Livro (v1.1)
// Habilidades de Universais, Combatente, Especialista, Ocultista + Rituais
// Arquivo separado para organização — importe antes do script principal
// =============================================================================

const HABS_LIVRO = [
  // ── UNIVERSAL ─────────────────────────────────────────────────────────────
  {
    classe: 'Universal',
    nome: 'Aumento de Atributo',
    custo: '—',
    nex: '20%',
    desc: 'Aumente um atributo à sua escolha em +1. Você não pode aumentar um atributo além de 5 desta forma. Disponível em NEX 20%, 50%, 80% e 95%.'
  },
  {
    classe: 'Universal',
    nome: 'Grau de Treinamento',
    custo: '—',
    nex: '35%',
    desc: 'Aumente o grau de treinamento de várias perícias treinadas em um (de treinado para veterano ou de veterano para expert). Disponível em NEX 35% e 70% (Combatente: 2 + Int; Especialista: 5 + Int; Ocultista: 4 + Int).'
  },
  {
    classe: 'Universal',
    nome: 'Aprender Ritual',
    custo: '—',
    nex: '5%',
    desc: 'Aprende um ritual de qualquer círculo que possa lançar. (Ocultista: ao avançar de NEX, aprende um ritual de qualquer círculo que possa lançar. Esses rituais não contam no limite de rituais conhecidos.)'
  },

  // ── COMBATENTE ────────────────────────────────────────────────────────────
  {
    classe: 'Combatente',
    nome: 'Armamento Pesado',
    custo: '—',
    nex: '15%',
    desc: 'Você recebe proficiência com armas pesadas. Pré-requisito: For 2.'
  },
  {
    classe: 'Combatente',
    nome: 'Artista Marcial',
    custo: '—',
    nex: '15%',
    desc: 'Seus ataques desarmados causam 1d6 pontos de dano, podem causar dano letal e contam como armas ágeis. Em NEX 35%, o dano aumenta para 1d8 e, em NEX 70%, para 1d10.'
  },
  {
    classe: 'Combatente',
    nome: 'Ataque de Oportunidade',
    custo: '1 PE + reação',
    nex: '15%',
    desc: 'Sempre que um ser sair voluntariamente de um espaço adjacente ao seu, você pode gastar uma reação e 1 PE para fazer um ataque corpo a corpo contra ele.'
  },
  {
    classe: 'Combatente',
    nome: 'Combater com Duas Armas',
    custo: '—',
    nex: '15%',
    desc: 'Se estiver usando duas armas (e pelo menos uma for leve) e fizer a ação agredir, você pode fazer dois ataques, um com cada arma. Se fizer isso, sofre –2 em todos os testes de ataque até o seu próximo turno. Pré-requisitos: Agi 3, treinado em Luta ou Pontaria.'
  },
  {
    classe: 'Combatente',
    nome: 'Combate Defensivo',
    custo: '—',
    nex: '15%',
    desc: 'Quando usa a ação agredir, você pode combater defensivamente. Se fizer isso, até seu próximo turno, sofre –2 em todos os testes de ataque, mas recebe +5 na Defesa. Pré-requisito: Int 2.'
  },
  {
    classe: 'Combatente',
    nome: 'Golpe Demolidor',
    custo: '1 PE',
    nex: '15%',
    desc: 'Quando usa a manobra quebrar ou ataca um objeto, você pode gastar 1 PE para causar dois dados de dano extra do mesmo tipo de sua arma. Pré-requisitos: For 2, treinado em Luta.'
  },
  {
    classe: 'Combatente',
    nome: 'Golpe Pesado',
    custo: '—',
    nex: '15%',
    desc: 'O dano de suas armas corpo a corpo aumenta em mais um dado do mesmo tipo.'
  },
  {
    classe: 'Combatente',
    nome: 'Incansável',
    custo: '2 PE',
    nex: '15%',
    desc: 'Uma vez por cena, você pode gastar 2 PE para fazer uma ação de investigação adicional, mas deve usar Força ou Agilidade como atributo-base do teste.'
  },
  {
    classe: 'Combatente',
    nome: 'Presteza Atlética',
    custo: '1 PE',
    nex: '15%',
    desc: 'Quando faz um teste de facilitar a investigação, você pode gastar 1 PE para usar Força ou Agilidade no lugar do atributo-base da perícia. Se passar no teste, o próximo aliado que usar seu bônus também recebe +2 no teste.'
  },
  {
    classe: 'Combatente',
    nome: 'Proteção Pesada',
    custo: '—',
    nex: '30%',
    desc: 'Você recebe proficiência com Proteções Pesadas. Pré-requisito: NEX 30%.'
  },
  {
    classe: 'Combatente',
    nome: 'Reflexos Defensivos',
    custo: '—',
    nex: '15%',
    desc: 'Você recebe +2 em Defesa e em testes de resistência. Pré-requisitos: Agi 2.'
  },
  {
    classe: 'Combatente',
    nome: 'Saque Rápido',
    custo: '—',
    nex: '15%',
    desc: 'Você pode sacar ou guardar itens como uma ação livre (em vez de ação de movimento). Além disso, caso esteja usando a regra opcional de contagem de munição, uma vez por rodada pode recarregar uma arma de disparo como uma ação livre. Pré-requisito: treinado em Iniciativa.'
  },
  {
    classe: 'Combatente',
    nome: 'Segurar o Gatilho',
    custo: '2 PE+',
    nex: '60%',
    desc: 'Sempre que acerta um ataque com uma arma de fogo, pode fazer outro ataque com a mesma arma contra o mesmo alvo, pagando 2 PE por cada ataque já realizado no turno. Pré-requisito: NEX 60%.'
  },
  {
    classe: 'Combatente',
    nome: 'Sentido Tático',
    custo: '2 PE + ação de mov.',
    nex: '15%',
    desc: 'Você pode gastar uma ação de movimento e 2 PE para analisar o ambiente. Se fizer isso, recebe um bônus em Defesa e em testes de resistência igual ao seu Intelecto até o final da cena. Pré-requisitos: Int 2, treinado em Percepção e Tática.'
  },
  {
    classe: 'Combatente',
    nome: 'Tanque de Guerra',
    custo: '—',
    nex: '30%',
    desc: 'Se estiver usando uma proteção pesada, a Defesa e a resistência a dano que ela fornece aumentam em +2. Pré-requisito: Proteção Pesada.'
  },
  {
    classe: 'Combatente',
    nome: 'Tiro Certeiro',
    custo: '—',
    nex: '15%',
    desc: 'Se estiver usando uma arma de disparo, você soma sua Agilidade nas rolagens de dano e ignora a penalidade contra alvos envolvidos em combate corpo a corpo (mesmo se não usar a ação mirar). Pré-requisito: treinado em Pontaria.'
  },
  {
    classe: 'Combatente',
    nome: 'Tiro de Cobertura',
    custo: '1 PE + ação padrão',
    nex: '15%',
    desc: 'Você pode gastar uma ação padrão e 1 PE para disparar uma arma de fogo na direção de um personagem no alcance da arma para forçá-lo a se proteger. Faça um teste de Pontaria contra a Vontade do alvo. Se vencer, até o início do seu próximo turno o alvo não pode sair do lugar onde está e sofre –5 em testes de ataque. Este é um efeito de medo.'
  },
  {
    classe: 'Combatente',
    nome: 'Transcender',
    custo: '—',
    nex: '15%',
    desc: 'Escolha um poder paranormal. Você recebe o poder escolhido, mas não ganha Sanidade neste aumento de NEX. Você pode escolher este poder várias vezes.'
  },
  {
    classe: 'Combatente',
    nome: 'Treinamento em Perícia',
    custo: '—',
    nex: '15%',
    desc: 'Escolha duas perícias. Você se torna treinado nessas perícias. A partir de NEX 35%, você pode escolher perícias nas quais já é treinado para se tornar veterano. A partir de NEX 70%, pode escolher perícias nas quais já é veterano para se tornar expert. Você pode escolher este poder várias vezes.'
  },

  // ── ESPECIALISTA ──────────────────────────────────────────────────────────
  {
    classe: 'Especialista',
    nome: 'Artista Marcial',
    custo: '—',
    nex: '15%',
    desc: 'Seus ataques desarmados causam 1d6 pontos de dano, podem causar dano letal e contam como armas ágeis. Em NEX 35%, o dano aumenta para 1d8 e, em NEX 70%, para 1d10.'
  },
  {
    classe: 'Especialista',
    nome: 'Balística Avançada',
    custo: '—',
    nex: '15%',
    desc: 'Você recebe proficiência com armas táticas de fogo e +2 em rolagens de dano com essas armas.'
  },
  {
    classe: 'Especialista',
    nome: 'Conhecimento Aplicado',
    custo: '2 PE',
    nex: '15%',
    desc: 'Quando faz um teste de perícia (exceto Luta e Pontaria), você pode gastar 2 PE para mudar o atributo-base da perícia para Int. Pré-requisito: Int 2.'
  },
  {
    classe: 'Especialista',
    nome: 'Eclético',
    custo: '2 PE',
    nex: '5%',
    desc: 'Quando faz um teste de uma perícia, você pode gastar 2 PE para receber os benefícios de ser treinado nesta perícia.'
  },
  {
    classe: 'Especialista',
    nome: 'Hacker',
    custo: '—',
    nex: '15%',
    desc: 'Você recebe +5 em testes de Tecnologia para invadir sistemas e diminui o tempo necessário para hackear qualquer sistema para uma ação completa. Pré-requisito: treinado em Tecnologia.'
  },
  {
    classe: 'Especialista',
    nome: 'Mãos Rápidas',
    custo: '1 PE',
    nex: '15%',
    desc: 'Ao fazer um teste de Crime, você pode pagar 1 PE para fazê-lo como uma ação livre. Pré-requisitos: Agi 3, treinado em Crime.'
  },
  {
    classe: 'Especialista',
    nome: 'Mochila de Utilidades',
    custo: '—',
    nex: '15%',
    desc: 'Um item a sua escolha (exceto armas) conta como uma categoria abaixo e ocupa 1 espaço a menos.'
  },
  {
    classe: 'Especialista',
    nome: 'Movimento Tático',
    custo: '1 PE',
    nex: '15%',
    desc: 'Você pode gastar 1 PE para ignorar a penalidade em deslocamento por terreno difícil e por escalar até o final do turno. Pré-requisito: treinado em Atletismo.'
  },
  {
    classe: 'Especialista',
    nome: 'Na Trilha Certa',
    custo: '1 PE+',
    nex: '15%',
    desc: 'Sempre que tiver sucesso em um teste para procurar pistas, você pode gastar 1 PE para receber +2 no próximo teste. Os custos e os bônus são cumulativos.'
  },
  {
    classe: 'Especialista',
    nome: 'Nerd',
    custo: '2 PE',
    nex: '15%',
    desc: 'Você é um repositório de conhecimento útil (e inútil). Uma vez por cena, pode gastar 2 PE para fazer um teste de Atualidades (DT 20). Se passar, recebe uma informação útil para essa cena (uma dica para uma pista ou uma fraqueza de um inimigo).'
  },
  {
    classe: 'Especialista',
    nome: 'Ninja Urbano',
    custo: '—',
    nex: '15%',
    desc: 'Você recebe proficiência com armas táticas de ataque corpo a corpo e de disparo (exceto de fogo) e +2 em rolagens de dano com essas armas.'
  },
  {
    classe: 'Especialista',
    nome: 'Pensamento Ágil',
    custo: '2 PE',
    nex: '15%',
    desc: 'Uma vez por rodada, durante uma cena de investigação, você pode gastar 2 PE para fazer uma ação de procurar pistas adicional.'
  },
  {
    classe: 'Especialista',
    nome: 'Perito',
    custo: '2 PE+',
    nex: '5%',
    desc: 'Escolha duas perícias nas quais você é treinado (exceto Luta e Pontaria). Quando faz um teste de uma dessas perícias, você pode gastar 2 PE para somar +1d6 no resultado do teste. Conforme avança de NEX, você pode gastar +1 PE para aumentar o dado de bônus (em NEX 55%, +1d10).'
  },
  {
    classe: 'Especialista',
    nome: 'Perito em Explosivos',
    custo: '—',
    nex: '15%',
    desc: 'Você soma seu Intelecto na DT para resistir aos seus explosivos e pode excluir dos efeitos da explosão um número de alvos igual ao seu valor de Intelecto.'
  },
  {
    classe: 'Especialista',
    nome: 'Primeira Impressão',
    custo: '—',
    nex: '15%',
    desc: 'Você recebe +2d6 no primeiro teste de Diplomacia, Enganação, Intimidação ou Intuição que fizer em uma cena.'
  },
  {
    classe: 'Especialista',
    nome: 'Transcender',
    custo: '—',
    nex: '15%',
    desc: 'Escolha um poder paranormal. Você recebe o poder escolhido, mas não ganha Sanidade neste aumento de NEX. Você pode escolher este poder várias vezes.'
  },
  {
    classe: 'Especialista',
    nome: 'Treinamento em Perícia',
    custo: '—',
    nex: '15%',
    desc: 'Escolha duas perícias. Você se torna treinado nessas perícias. A partir de NEX 35%, você pode escolher perícias nas quais já é treinado para se tornar veterano. A partir de NEX 70%, pode escolher perícias nas quais já é veterano para se tornar expert. Você pode escolher este poder várias vezes.'
  },

  // ── OCULTISTA ─────────────────────────────────────────────────────────────
  {
    classe: 'Ocultista',
    nome: 'Camuflar Ocultismo',
    custo: '2 PE',
    nex: '15%',
    desc: 'Você pode gastar uma ação livre para esconder símbolos e sigilos em objetos ou em sua pele. Além disso, quando lança um ritual, pode gastar +2 PE para lançá-lo sem usar componentes ritualísticos e sem gesticular. Outros seres só perceberão que você lançou um ritual se passarem num teste de Ocultismo (DT 25).'
  },
  {
    classe: 'Ocultista',
    nome: 'Criar Selo',
    custo: 'PE do ritual',
    nex: '15%',
    desc: 'Você sabe fabricar selos paranormais de rituais que conheça. Fabricar um selo gasta uma ação de interlúdio e um número de PE iguais ao custo de conjurar o ritual. Você pode ter um número máximo de selos criados igual à sua Presença.'
  },
  {
    classe: 'Ocultista',
    nome: 'Envolto em Mistério',
    custo: '—',
    nex: '15%',
    desc: 'Sua aparência e postura assombrosas o permitem manipular e assustar pessoas ignorantes ou supersticiosas. Você recebe +5 em Enganação e Intimidação contra pessoas não treinadas em Ocultismo.'
  },
  {
    classe: 'Ocultista',
    nome: 'Especialista em Elemento',
    custo: '—',
    nex: '15%',
    desc: 'Escolha um elemento. A DT para resistir aos seus rituais desse elemento aumenta em +2.'
  },
  {
    classe: 'Ocultista',
    nome: 'Ferramentas Paranormais',
    custo: '—',
    nex: '15%',
    desc: 'Você reduz a categoria de um item paranormal em I e pode ativar itens paranormais sem pagar seu custo em PE.'
  },
  {
    classe: 'Ocultista',
    nome: 'Fluxo de Poder',
    custo: '—',
    nex: '60%',
    desc: 'Você pode manter dois efeitos sustentados de rituais ativos simultaneamente com apenas uma ação livre, pagando o custo de cada efeito separadamente. Pré-requisito: NEX 60%.'
  },
  {
    classe: 'Ocultista',
    nome: 'Guiado pelo Paranormal',
    custo: '2 PE',
    nex: '15%',
    desc: 'Uma vez por cena, você pode gastar 2 PE para fazer uma ação de investigação adicional.'
  },
  {
    classe: 'Ocultista',
    nome: 'Identificação Paranormal',
    custo: '—',
    nex: '15%',
    desc: 'Você recebe +10 em testes de Ocultismo para identificar criaturas, objetos ou rituais.'
  },
  {
    classe: 'Ocultista',
    nome: 'Improvisar Componentes',
    custo: '—',
    nex: '15%',
    desc: 'Uma vez por cena, você pode gastar uma ação completa para fazer um teste de Investigação (DT 15). Se passar, encontra objetos que podem servir como componentes ritualísticos de um elemento à sua escolha.'
  },
  {
    classe: 'Ocultista',
    nome: 'Intuição Paranormal',
    custo: '—',
    nex: '15%',
    desc: 'Sempre que usa a ação facilitar investigação, você soma seu Intelecto ou Presença no teste (à sua escolha).'
  },
  {
    classe: 'Ocultista',
    nome: 'Mestre em Elemento',
    custo: '1 PE a menos',
    nex: '45%',
    desc: 'Escolha um elemento. O custo para lançar rituais desse elemento diminui em –1 PE. Pré-requisitos: Especialista em Elemento no elemento escolhido, NEX 45%.'
  },
  {
    classe: 'Ocultista',
    nome: 'Ritual Potente',
    custo: '—',
    nex: '15%',
    desc: 'Você soma seu Intelecto nas rolagens de dano ou nos efeitos de cura de seus rituais. Pré-requisito: Int 2.'
  },
  {
    classe: 'Ocultista',
    nome: 'Ritual Predileto',
    custo: '1 PE a menos',
    nex: '15%',
    desc: 'Escolha um ritual que você conhece. Você reduz em –1 PE o custo do ritual. Essa redução se acumula com reduções fornecidas por outras fontes.'
  },
  {
    classe: 'Ocultista',
    nome: 'Tatuagem Ritualística',
    custo: '—',
    nex: '15%',
    desc: 'Símbolos marcados em sua pele reduzem em –1 PE o custo de rituais de alcance pessoal que têm você como alvo.'
  },
  {
    classe: 'Ocultista',
    nome: 'Transcender',
    custo: '—',
    nex: '15%',
    desc: 'Escolha um poder paranormal. Você recebe o poder escolhido, mas não ganha Sanidade neste aumento de NEX. Você pode escolher este poder várias vezes.'
  },
  {
    classe: 'Ocultista',
    nome: 'Treinamento em Perícia',
    custo: '—',
    nex: '15%',
    desc: 'Escolha duas perícias. Você se torna treinado nessas perícias. A partir de NEX 35%, você pode escolher perícias nas quais já é treinado para se tornar veterano. A partir de NEX 70%, pode escolher perícias nas quais já é veterano para se tornar expert. Você pode escolher este poder várias vezes.'
  },
];

// =============================================================================
// RITUAIS DO LIVRO — Lista completa com descrições, discente e verdadeiro
// Elemento: Conhecimento | Energia | Morte | Sangue | Medo
// Círculo: '1' | '2' | '3' | '4'
// =============================================================================

const RITUAIS_LIVRO = [
  // ── 1º CÍRCULO — CONHECIMENTO ─────────────────────────────────────────────
  {
    nome: 'Amaldiçoar Arma',
    elem: 'Conhecimento',
    circ: '1',
    exec: 'padrão',
    alc: 'toque',
    dur: 'cena',
    pe: 1,
    desc: 'Quando aprender este ritual, escolha um elemento entre Conhecimento, Energia, Morte e Sangue. Você imbui a arma ou munições com o elemento, fazendo com que causem +1d6 de dano do tipo do elemento.',
    d_pe: '2',
    d_desc: 'Muda o bônus de dano para +2d6. Requer 2º círculo.',
    v_pe: '5',
    v_desc: 'Muda o bônus de dano para +4d6. Requer 3º círculo e afinidade.',
  },
  {
    nome: 'Compreensão Paranormal',
    elem: 'Conhecimento',
    circ: '1',
    exec: 'padrão',
    alc: 'toque',
    dur: 'instantânea (veja texto)',
    pe: 1,
    desc: 'O ritual confere a você compreensão sobrenatural da linguagem. Se tocar um objeto contendo informação (ou livro, um dispositivo com uma gravação), você entende as palavras mesmo que não conheça seu significado.',
    d_pe: '',
    d_desc: '',
    v_pe: '',
    v_desc: '',
  },
  {
    nome: 'Enfeitiçar',
    elem: 'Conhecimento',
    circ: '1',
    exec: 'padrão',
    alc: 'curto',
    dur: 'cena',
    pe: 1,
    desc: 'Este ritual torna o alvo prestativo. Ele não fica sob seu controle, mas percebe suas palavras e ações da maneira mais favorável possível. Você recebe um bônus de +10 em testes de Diplomacia com ele. Um alvo hostil ou em combate recebe +5 no teste de resistência. Resistência: Vontade anula.',
    d_pe: '2',
    d_desc: 'Em vez do normal, você sugere uma ação para o alvo e ele obedece. A sugestão deve parecer aceitável. Quando o alvo executa a ação, o efeito termina. Requer 2º círculo.',
    v_pe: '5',
    v_desc: 'Afeta todos os alvos dentro do alcance. Requer 3º círculo.',
  },
  {
    nome: 'Perturbação',
    elem: 'Conhecimento',
    circ: '1',
    exec: 'padrão',
    alc: 'curto',
    dur: '1 rodada',
    pe: 1,
    desc: 'Você dá uma ordem que o alvo deve obedecer em seu próprio turno da melhor maneira possível. Escolha: Fuja (afaste de você), Largue (solta itens), Pare (fica pasmo), Sente-se (senta no chão) ou Venha (aproxima de você). Resistência: Vontade anula.',
    d_pe: '2',
    d_desc: 'Muda o alvo para "1 ser" e adiciona o comando "Sofra" (3d8 de dano de Conhecimento, alvo fica abalado). Requer 2º círculo.',
    v_pe: '5',
    v_desc: 'Muda o alvo para "até 5 seres" ou adiciona o comando "Ataque" (alvo deve usar ação agredir contra um alvo à sua escolha em alcance médio). Requer 3º círculo e afinidade.',
  },
  {
    nome: 'Ouvir os Sussurros',
    elem: 'Conhecimento',
    circ: '1',
    exec: 'completa',
    alc: 'pessoal',
    dur: 'instantânea',
    pe: 1,
    desc: 'O ritual conecta você com os sussurros do Outro Lado. Faça uma pergunta sobre um evento que você está prestes a fazer (na mesma cena) que possa ser respondida com "sim" ou "não". O mestre rola 1d6 em segredo; com um resultado de 2 a 6, o ritual funciona.',
    d_pe: '2',
    d_desc: 'Muda a execução para 1 minuto. Em vez do normal, você pode consultar os ecos fazendo uma pergunta sobre um evento que poderá acontecer até um dia no futuro. Requer 2º círculo.',
    v_pe: '5',
    v_desc: 'Muda a execução para 10 minutos e a duração para 5 rodadas. Você pode fazer uma pergunta por rodada. Requer 3º círculo.',
  },
  {
    nome: 'Tecer Ilusão',
    elem: 'Conhecimento',
    circ: '1',
    exec: 'padrão',
    alc: 'médio',
    dur: 'cena',
    pe: 1,
    desc: 'Este ritual cria uma ilusão visual ou sonora. O ritual cria apenas imagens ou sons simples, com volume equivalente à voz de uma pessoa para cada cubo de 1,5m no efeito. Não é possível criar cheiros, texturas ou temperaturas. Resistência: Vontade desacredita.',
    d_pe: '2',
    d_desc: 'Muda o efeito para até 8 cubos de 1,5m e a duração para sustentada. Você pode criar ilusões de imagem e sons combinados, odores e sensações térmicas. Requer 2º círculo.',
    v_pe: '5',
    v_desc: 'Você cria a ilusão de um perigo mortal. Quando conjurado, e no início de cada um de seus turnos, um alvo interagindo com a ilusão deve fazer um teste de Vontade; se falhar, sofre 6d6 pontos de dano de Conhecimento. Requer 3º círculo.',
  },
  {
    nome: 'Terceiro Olho',
    elem: 'Conhecimento',
    circ: '1',
    exec: 'padrão',
    alc: 'pessoal',
    dur: 'cena',
    pe: 1,
    desc: 'Seus olhos se enchem de sigilos e você passa a enxergar auras paranormais em alcance longo. Rituais, itens amaldiçoados e criaturas etéreas tornam-se visíveis. Você sabe imediatamente a aura e seu poder aproximado — rituais de 1º círculo e criaturas de VD até 80 são aura fraca; rituais de 2º e 3º círculos e criaturas de VD até 81-280 e criaturas de VD 281 ou maior uma aura poderosa. Além disso, você pode gastar uma ação de movimento para descobrir se um ser que possa ver em alcance médio tem poderes paranormais ou se é capaz de conjurar rituais.',
    d_pe: '2',
    d_desc: 'Muda a duração para 1 dia. Requer 2º círculo.',
    v_pe: '5',
    v_desc: 'Também pode enxergar objetos e seres invisíveis, que aparecem como formas translúcidas. Requer 3º círculo.',
  },

  // ── 1º CÍRCULO — ENERGIA ──────────────────────────────────────────────────
  {
    nome: 'Amaldiçoar Tecnologia',
    elem: 'Energia',
    circ: '1',
    exec: 'padrão',
    alc: 'toque',
    dur: 'cena',
    pe: 1,
    desc: 'Você imbui o alvo (acessório ou arma de fogo) com Energia, fazendo-o funcionar acima de sua capacidade. O item recebe uma modificação a sua escolha.',
    d_pe: '2',
    d_desc: 'Muda para duas modificações. Requer 2º círculo.',
    v_pe: '5',
    v_desc: 'Muda para três modificações. Requer 3º círculo e afinidade.',
  },
  {
    nome: 'Coincidência Forçada',
    elem: 'Energia',
    circ: '1',
    exec: 'padrão',
    alc: 'curto',
    dur: 'cena',
    pe: 1,
    desc: 'Você manipula os caminhos do caos para que um alvo tenha sorte. O alvo recebe +2 em testes de perícias.',
    d_pe: '2',
    d_desc: 'Muda o alvo para aliados à sua escolha. Requer 2º círculo.',
    v_pe: '5',
    v_desc: 'Muda o alvo para aliados à sua escolha e + bônus para +5. Requer 3º círculo e afinidade.',
  },
  {
    nome: 'Eletrocussão',
    elem: 'Energia',
    circ: '1',
    exec: 'padrão',
    alc: 'curto',
    dur: 'instantânea',
    pe: 1,
    desc: 'Você manifesta e dispara uma corrente elétrica contra o alvo, que sofre 3d6 pontos de dano de eletricidade e fica vulnerável por uma rodada. Se passar na resistência (Fortitude), sofre apenas metade do dano e evita a condição. Contra objetos eletrônicos, causa o dobro de dano e ignora resistência.',
    d_pe: '2',
    d_desc: 'Muda o alvo para "área: linha de 30m". Você dispara um poderoso raio que causa 6d6 pontos de dano de Energia em todos os seres e objetos livres na área. Requer 2º círculo.',
    v_pe: '5',
    v_desc: 'Muda o alvo para "alvos escolhidos". Em vez do normal, você dispara vários relâmpagos, um para cada alvo, causando 8d6 pontos de dano de Energia em cada. Requer 3º círculo.',
  },
  {
    nome: 'Embaralhar',
    elem: 'Energia',
    circ: '1',
    exec: 'padrão',
    alc: 'pessoal',
    dur: 'cena',
    pe: 1,
    desc: 'Você cria três cópias ilusórias suas, como hologramas extremamente realistas. Você recebe +6 na Defesa. Cada vez que um ataque contra você erra, uma das imagens desaparece e o bônus na Defesa diminui em 2.',
    d_pe: '2',
    d_desc: 'Muda o número de cópias para 5 (e o bônus na Defesa para +10). Requer 2º círculo.',
    v_pe: '5',
    v_desc: 'Muda o número de cópias para 8 (e o bônus na Defesa para +16). Toda vez que uma cópia é destruída, emite um clarão de luz — o ser que a destruiu fica ofuscado por uma rodada. Requer 3º círculo.',
  },
  {
    nome: 'Luz',
    elem: 'Energia',
    circ: '1',
    exec: 'padrão',
    alc: 'curto',
    dur: 'cena',
    pe: 1,
    desc: 'Você emite luz de cores brilhantes e brilhantes (mas não produz calor) em uma área com 9m de raio. O objeto pode ser guardado (em um bolso, por exemplo) para interromper a luz, e manter a função caso o objeto seja revelado. Se o alvo for um objeto vivo ou uma pessoa involuntária, ela tem direito a um teste de Vontade para anular o efeito. Resistência: Vontade anula.',
    d_pe: '2',
    d_desc: 'Muda o alcance para longo e o efeito para esfera brilhante. Essa esfera flutuantes pode pousar onde quiser dentro do alcance. Você pode enviar uma esfera à frente, outra para trás, outra para cima e manter uma parte de você, por exemplo. Uma vez por rodada, você pode mover as esferas em ação livre. Cada esfera ilumina uma área de 6m de raio. Não produz calor. Se uma esfera ocupar o espaço de um ser, ela é ofuscada e sua silhueta pode ser vista claramente. Requer 2º círculo.',
    v_pe: '5',
    v_desc: 'A luz é cálida como a do Sol. Dentro da área seus aliados recebem +2 em testes de Vontade e seus inimigos ficam ofuscados. Requer 3º círculo.',
  },
  {
    nome: 'Polarização Caótica',
    elem: 'Energia',
    circ: '1',
    exec: 'padrão',
    alc: 'curto',
    dur: 'sustentada',
    pe: 1,
    desc: 'Você gera uma aura magnética sobrenatural. Escolha: Atrair (puxa objetos metálicos de espaço 2 ou menor para suas mãos) ou Repelir (repele projéteis e armas de arremesso, recebendo resistência a balístico, corte, impacto e perfuração 5). Resistência: Vontade anula.',
    d_pe: '2',
    d_desc: 'A energia magnética arremessa até 10 objetos ou um total de 10 espaços. Objetos arremessados podem atingir seres em seu caminho causando dano. Requer 2º círculo.',
    v_pe: '5',
    v_desc: 'Muda o alcance para médio. Você pode usar uma ação de movimento para fazer com que a força magnética levite e mova um ser ou objeto de espaço 10 ou menor por até 9m em qualquer direção.',
  },

  // ── 1º CÍRCULO — MORTE ────────────────────────────────────────────────────
  {
    nome: 'Cicatrização',
    elem: 'Morte',
    circ: '1',
    exec: 'padrão',
    alc: 'toque',
    dur: 'instantânea',
    pe: 1,
    desc: 'Você acelera o tempo ao redor das feridas do alvo, que cicatrizam instantaneamente. O alvo recupera 3d8+5 PV, mas envelhece 1 ano automaticamente.',
    d_pe: '2',
    d_desc: 'Aumenta a cura para 5d8+5 PV. Requer 2º círculo.',
    v_pe: '9',
    v_desc: 'Muda o alcance para "curto", o alvo para "seres escolhidos" e aumenta a cura para 7d8+7 PV. Requer 4º círculo e afinidade com Morte.',
  },
  {
    nome: 'Consumir Manancial',
    elem: 'Morte',
    circ: '1',
    exec: 'padrão',
    alc: 'pessoal',
    dur: 'instantânea',
    pe: 1,
    desc: 'Você suga uma pequena porção do tempo de vida de plantas, insetos e até mesmo do solo ao redor, gerando lodo e recebendo 3d6 pontos de vida temporários. Os PV temporários desaparecem ao final da cena.',
    d_pe: '2',
    d_desc: 'Muda os PV temporários recebidos para 6d6. Requer 2º círculo.',
    v_pe: '5',
    v_desc: 'Muda o alvo para "área: esfera com 6m de raio centrada em você". Você suga energia de todos os seres vivos na área, causando 3d6 pontos de dano de Morte em cada um e recebendo PV temporários iguais ao dano total causado. Requer 3º círculo e afinidade.',
  },
  {
    nome: 'Decadência',
    elem: 'Morte',
    circ: '1',
    exec: 'padrão',
    alc: 'toque',
    dur: 'instantânea',
    pe: 1,
    desc: 'Espirais de trevas envolvem sua mão e definham o alvo, que sofre 2d8+2 pontos de dano de Morte. Resistência: Fortitude reduz à metade.',
    d_pe: '2',
    d_desc: 'Muda a resistência para "nenhuma" e o dano para 3d8+3. Como parte da execução, você transfere as espirais para uma arma e faz um ataque corpo a corpo contra o alvo. Se acertar, causa o dano da arma e do ritual somados. Requer 2º círculo.',
    v_pe: '5',
    v_desc: 'Muda o alcance para pessoal, o alvo para "área: explosão com 6m de raio" e o dano para 8d8+8. As espirais afetam todos os seres na área. Requer 3º círculo.',
  },
  {
    nome: 'Definhar',
    elem: 'Morte',
    circ: '1',
    exec: 'padrão',
    alc: 'curto',
    dur: 'cena',
    pe: 1,
    desc: 'Você dispara uma lufada de cinzas que drena as forças do alvo. O alvo fica fatigado. Se passar no teste de resistência (Fortitude), em vez disso fica vulnerável.',
    d_pe: '2',
    d_desc: 'Em vez do normal, o alvo fica exausto. Se passar na resistência, fica fatigado. Requer 2º círculo.',
    v_pe: '5',
    v_desc: 'Como discente, mas muda o alvo para "até 5 seres". Requer 3º círculo e afinidade com Morte.',
  },
  {
    nome: 'Espirais da Perdição',
    elem: 'Morte',
    circ: '1',
    exec: 'padrão',
    alc: 'curto',
    dur: 'cena',
    pe: 1,
    desc: 'Espirais surgem no corpo do alvo, tornando seus movimentos lentos. O alvo sofre –2 em testes de ataque.',
    d_pe: '2',
    d_desc: 'Muda a penalidade para –4. Requer 2º círculo.',
    v_pe: '8',
    v_desc: 'Muda a penalidade para –4 e o alvo para "seres escolhidos". Requer 3º círculo.',
  },
  {
    nome: 'Nuvem de Cinzas',
    elem: 'Morte',
    circ: '1',
    exec: 'padrão',
    alc: 'curto',
    dur: 'cena',
    pe: 1,
    desc: 'Uma nuvem de fuligem espessa eleva-se de um ponto a sua escolha, obscurecendo toda a visão — seres a até 1,5m têm camuflagem e seres a partir de 3m têm camuflagem total. Um vento forte dispersa a nuvem em 4 rodadas.',
    d_pe: '2',
    d_desc: 'Você pode escolher seres no alcance ao conjurar o ritual; eles enxergam através do efeito. Requer 2º círculo.',
    v_pe: '5',
    v_desc: 'Além do normal, a nuvem fica espessa, quase sólida. Qualquer ser dentro dela tem seu deslocamento reduzido para 3m e sofre –2 em testes de ataque. Requer 3º círculo.',
  },

  // ── 1º CÍRCULO — SANGUE ───────────────────────────────────────────────────
  {
    nome: 'Arma Atroz',
    elem: 'Sangue',
    circ: '1',
    exec: 'padrão',
    alc: 'toque',
    dur: 'sustentada',
    pe: 1,
    desc: 'A arma é recoberta por veias carmesim e passa a exalar uma aura de violência. Ela fornece +2 em testes de ataque e +1 na margem de ameaça.',
    d_pe: '2',
    d_desc: 'Muda o bônus para +5 em testes de ataque. Requer 2º círculo.',
    v_pe: '5',
    v_desc: 'Muda o bônus para +5 em testes de ataque e +2 na margem de ameaça e no multiplicador de crítico. Requer 3º círculo e afinidade.',
  },
  {
    nome: 'Armadura de Sangue',
    elem: 'Sangue',
    circ: '1',
    exec: 'padrão',
    alc: 'pessoal',
    dur: 'cena',
    pe: 1,
    desc: 'Seu sangue escorre para fora do corpo, cobrindo-o sob a forma de uma carapaça que fornece +5 em Defesa. Esse bônus é cumulativo com outros rituais, mas não com bônus fornecido por equipamento. Você também recebe +10 em testes de Fortitude.',
    d_pe: '5',
    d_desc: 'Muda o efeito para "fornece +10 na Defesa e resistência a balístico, corte, impacto e perfuração 5". Requer 3º círculo.',
    v_pe: '9',
    v_desc: 'Muda o efeito para "fornece +15 na Defesa e resistência a balístico, corte, impacto e perfuração 10". Requer 4º círculo e afinidade.',
  },
  {
    nome: 'Corpo Adaptado',
    elem: 'Sangue',
    circ: '1',
    exec: 'padrão',
    alc: 'toque',
    dur: 'cena',
    pe: 1,
    desc: 'Este ritual modifica a biologia do alvo para permitir a sobrevivência em ambientes hostis. O alvo fica imune a calor extremo e ambientes hostis, podendo respirar ar rarefeito e fumaça densa.',
    d_pe: '2',
    d_desc: 'Muda a duração para 1 dia. Requer 2º círculo.',
    v_pe: '5',
    v_desc: 'Muda o alcance para "curto" ou para "pessoas ou animais escolhidos". Requer 3º círculo.',
  },
  {
    nome: 'Distorcer Aparência',
    elem: 'Sangue',
    circ: '1',
    exec: 'padrão',
    alc: 'pessoal',
    dur: 'cena',
    pe: 1,
    desc: 'Você modifica sua aparência de modo a parecer outra pessoa. Isso inclui altura, peso, tom de pele, cor de cabelo, timbre de voz, impressão digital, córnea etc. Você recebe +10 em testes de Enganação para disfarce. Resistência: Vontade desacredita.',
    d_pe: '2',
    d_desc: 'Muda o alcance para "curto" e o alvo para "1 ser". Um alvo involuntário pode anular o efeito com um teste de Vontade.',
    v_pe: '5',
    v_desc: 'Como em Discente, mas muda o alvo para "seres escolhidos". Requer 3º círculo.',
  },
  {
    nome: 'Fortalecimento Sensorial',
    elem: 'Sangue',
    circ: '1',
    exec: 'padrão',
    alc: 'pessoal',
    dur: 'cena',
    pe: 1,
    desc: 'Você potencializa seus sentidos, recebendo +2 em Investigação, Luta, Percepção e Pontaria.',
    d_pe: '2',
    d_desc: 'Além do normal, seus inimigos sofrem –2 em testes de ataque contra você. Requer 2º círculo.',
    v_pe: '5',
    v_desc: 'Além do normal, você apura seus sentidos para perceber qualquer perigo. Você fica imune às condições surpreendido e desprevenido e recebe +10 em Defesa e Reflexo. Requer 4º círculo e afinidade.',
  },
  {
    nome: 'Ódio Incontrolável',
    elem: 'Sangue',
    circ: '1',
    exec: 'padrão',
    alc: 'toque',
    dur: 'cena',
    pe: 1,
    desc: 'O alvo entra em um frenesi, recebendo +2 em testes de ataque e rolagens de dano corpo a corpo e resistência a balístico, corte, impacto e perfuração 5. Enquanto o efeito durar, o alvo não pode fazer nenhuma ação que exige calma e deve sempre atacar um alvo em sua rodada.',
    d_pe: '2',
    d_desc: 'Além do normal, sempre que o alvo usar a ação agredir, pode fazer um ataque corpo a corpo adicional contra o mesmo alvo.',
    v_pe: '5',
    v_desc: 'Muda o bônus de ataque e dano para +5 e o alvo passa a sofrer apenas metade do dano dos tipos balístico, corte, impacto e perfuração. Requer 3º círculo e afinidade.',
  },

  // ── 1º CÍRCULO — MEDO ────────────────────────────────────────────────────
  {
    nome: 'Cinerária',
    elem: 'Medo',
    circ: '1',
    exec: 'padrão',
    alc: 'curto',
    dur: 'cena',
    pe: 1,
    desc: 'Você manifesta uma névoa carregada de essência paranormal. Rituais conjurados dentro da névoa têm sua DT aumentada em +5. Área: 1d6 cubos de raio.',
    d_pe: '2',
    d_desc: 'Além do normal, rituais conjurados dentro da névoa custam –2 PE. Requer 2º círculo.',
    v_pe: '5',
    v_desc: 'Além do normal, rituais conjurados dentro da névoa causam dano maximizado. Requer 3º círculo.',
  },

  // ── 2º CÍRCULO — CONHECIMENTO ─────────────────────────────────────────────
  {
    nome: 'Aprimorar Mente',
    elem: 'Conhecimento',
    circ: '2',
    exec: 'padrão',
    alc: 'toque',
    dur: 'cena',
    pe: 2,
    desc: 'O alvo tem sua mente energizada por fagulhas do Conhecimento. Ele recebe +1 em Intelecto ou Presença, a escolha dele e um bônus adicional em PE.',
    d_pe: '3',
    d_desc: 'Muda o bônus para +2. Requer 3º círculo.',
    v_pe: '7',
    v_desc: 'Muda o bônus para +3. Requer 4º círculo e afinidade.',
  },
  {
    nome: 'Detecção de Ameaças',
    elem: 'Conhecimento',
    circ: '2',
    exec: 'padrão',
    alc: 'pessoal',
    dur: 'cena',
    pe: 3,
    desc: 'Você recebe uma percepção aguçada sobre perigos à sua volta (área de 18m de raio). Quando um ser hostil ou armadilha entra na área do efeito, você tem uma sensação de perigo e pode gastar uma ação de movimento para fazer um teste de Percepção (DT 20). Se passar, sabe a direção e distância do perigo.',
    d_pe: '3',
    d_desc: 'Além do normal, você não fica desprevenido contra perigos detectados e recebe +5 em testes de resistência contra armadilhas. Requer 3º círculo.',
    v_pe: '5',
    v_desc: 'Muda a duração para "1 dia" e concede os mesmos benefícios de discente. Requer 4º círculo.',
  },
  {
    nome: 'Esconder dos Olhos',
    elem: 'Conhecimento',
    circ: '2',
    exec: 'livre',
    alc: 'pessoal',
    dur: '1 rodada',
    pe: 3,
    desc: 'Você fica invisível, incluindo seu equipamento, recebendo camuflagem total e +15 em testes de Furtividade. O efeito termina se você faz um ataque ou usa uma habilidade hostil.',
    d_pe: '3',
    d_desc: 'Muda a duração para "sustentada". Em vez do normal, você gera uma esfera de invisibilidade. Você e todos os aliados a até 3m de você se tornam invisíveis. Requer 3º círculo.',
    v_pe: '7',
    v_desc: 'Muda a execução para "ação padrão", o alcance para "toque", o alvo para "1 ser" e a duração para "sustentada". O efeito não é dissipado caso o alvo faça um ataque ou ação hostil. Requer 4º círculo e afinidade.',
  },
  {
    nome: 'Invadir Mente',
    elem: 'Conhecimento',
    circ: '2',
    exec: 'padrão',
    alc: 'médio ou toque',
    dur: 'instantânea ou 1 dia',
    pe: 3,
    desc: 'Quando conjura este ritual, você conjura um efeito sutil, uma escolha: raio mental (usa os primeiros parâmetros do cabeçalho) ou ligação telepática (usa os segundos parâmetros). Rajada Mental: você infecta a mente do alvo com o Conhecimento proibido do Outro Lado, dilacerando o cérebro dele. O alvo sofre 6d6 pontos de dano. Ligação Telepática: você cria um elo mental entre duas pessoas. Resistência: Vontade parcial.',
    d_pe: '3',
    d_desc: 'Se Rajada Mental: aumenta o dano para 10d6. Se Ligação Telepática: você pode ver e ouvir pelos sentidos do alvo. Requer 3º círculo.',
    v_pe: '7',
    v_desc: 'Se Rajada Mental: dano para 10d6, alvo para "seres escolhidos". Se Ligação Telepática: você pode criar um vínculo mental entre até 5 pessoas. Requer 3º círculo.',
  },
  {
    nome: 'Localização',
    elem: 'Conhecimento',
    circ: '2',
    exec: 'padrão',
    alc: 'pessoal',
    dur: 'cena',
    pe: 3,
    desc: 'Este ritual pode encontrar uma pessoa ou objeto a sua escolha dentro de uma área de 90m de raio. Você pode pensar em termos gerais ("um policial") ou específicos ("a delegada Joana"). O ritual indica a direção e distância do mais próximo.',
    d_pe: '3',
    d_desc: 'Muda o alcance para "toque", o alvo para "1 pessoa" e a duração para "1 hora". Em vez do normal, a pessoa tocada descobre o caminho mais direto para entrar ou sair de um lugar. Requer 3º círculo.',
    v_pe: '7',
    v_desc: 'Aumenta a área para círculo de 1km de raio. Requer 4º círculo.',
  },

  // ── 2º CÍRCULO — ENERGIA ──────────────────────────────────────────────────
  {
    nome: 'Chamas do Caos',
    elem: 'Energia',
    circ: '2',
    exec: 'padrão',
    alc: 'curto',
    dur: 'cena',
    pe: 2,
    desc: 'Você manipula o calor e o fogo. Ao conjurar o ritual, escolha um dos seguintes efeitos. Chamejar: o alvo é uma arma corpo a corpo. Ele causa +1d6 pontos de dano de fogo por rodada e causa o mesmo dano a qualquer ser que o esteja empunhando ou vestindo. A critério do mestre, o objeto ou o ser pode pegar fogo. Extinguir: o alvo é uma chama de tamanho Grande ou menor, que é apagada. Ao se passar nesses testes, os turnos seguintes à chama desaparecem. Modelar: o alvo é uma chama de tamanho Grande ou menor. A cada rodada, você pode gastar uma ação livre para movimentá-la 9m em qualquer direção. Se atravessar o espaço ocupado por um ser, ela causa 3d6 pontos de dano de fogo nele. Um ser só pode sofrer dessa mesma vez por rodada.',
    d_pe: '3',
    d_desc: 'Muda a duração para "sustentada" e aumenta a resistência para Reflexos reduz à metade. Em vez do normal, você pode rodar a roda de fogo para projetar uma labareda, num alvo em alcance curto. O alvo sofre 4d6 pontos de dano de Energia (Reflexos reduz à metade). Requer 2º círculo.',
    v_pe: '7',
    v_desc: 'Como Discente, mas muda o alcance para 8d. Requer 3º círculo.',
  },
  {
    nome: 'Contenção Fantasmagórica',
    elem: 'Energia',
    circ: '2',
    exec: 'padrão',
    alc: 'médio',
    dur: 'cena',
    pe: 3,
    desc: 'Três laços de Energia surgem do chão e se enroscam no alvo, deixando-o agarrado. O alvo pode tentar se livrar com uma ação padrão e teste de Atletismo (DT do ritual). Por serem feitos de Energia, os laços afetam criaturas incorpóreas. Resistência: Reflexos anula.',
    d_pe: '3',
    d_desc: 'Aumenta o número de laços para 6, e você pode escolher o alvo de cada laço, com um mínimo de dois laços por alvo. Requer 3º círculo.',
    v_pe: '5',
    v_desc: 'Como discente, e cada laço destruído libera uma onda de choque que causa 2d6+2 pontos de dano de Energia no alvo agarrado. Requer 3º círculo e afinidade.',
  },
  {
    nome: 'Dissonância Acústica',
    elem: 'Energia',
    circ: '2',
    exec: 'padrão',
    alc: 'médio',
    dur: 'sustentada',
    pe: 3,
    desc: 'Você manipula a vibração do ar, criando uma área de dissonância sonora (esfera com 6m de raio). Enquanto estiverem na área, todos os seres ficam surdos. Essa dissonância impede que seres dentro da área conjurem rituais.',
    d_pe: '1',
    d_desc: 'Muda a área para "alvo: 1 objeto". Em vez do normal, o alvo emana uma área de silêncio com 3m de raio.',
    v_pe: '3',
    v_desc: 'Muda a duração para cena. Nenhum som pode deixar a área, mas seres dentro da área podem falar, ouvir e conjurar rituais normalmente. Requer 3º círculo.',
  },
  {
    nome: 'Sopro do Caos',
    elem: 'Energia',
    circ: '2',
    exec: 'padrão',
    alc: 'médio',
    dur: 'sustentada',
    pe: 2,
    desc: 'Você altera os movimentos de massas de ar de forma caótica. Ao conjurar o ritual, escolha um dos efeitos abaixo. Ascender: cria uma corrente de ar ascendente capaz de erguer do chão a um ser ou objeto Médio, fazendo-o flutuar para cima. Você pode gastar uma ação de movimento para subir ou descer até 6m por rodada. Derubar: Alvos involuntários têm direito a um teste de Fortitude no início de cada um de seus turnos para encerrar o efeito. Suprir: cria uma lufada de vento a partir de suas mãos que empurra um alvo em um alcance, mas no máximo de 4,5m. Vento: cria uma área de vento forte dentro da área.',
    d_pe: '3',
    d_desc: 'Passa a afetar alvos Enormes. Requer 2º círculo.',
    v_pe: '7',
    v_desc: 'Muda o alvo para "alvos escolhidos". Requer 4º círculo e afinidade.',
  },
  {
    nome: 'Tela de Ruído',
    elem: 'Energia',
    circ: '2',
    exec: 'padrão',
    alc: 'pessoal',
    dur: 'cena',
    pe: 2,
    desc: 'Este ritual cria uma película de energia que recebe 30 PV temporários, mas apenas contra dano balístico, corte, de impacto ou de perfuração. Alternativamente, você pode conjurar este ritual como uma reação quando sofrer dano, recebendo 15 apenas contra esse dano.',
    d_pe: '3',
    d_desc: 'Aumenta os PV temporário para 60 e a resistência para 30. Requer 2º círculo.',
    v_pe: '7',
    v_desc: 'Muda o alcance para curto e o alvo para 1 ser ou objeto Enorme ou menor. Em vez do normal, cria uma esfera imóvel e tremeluzente com o tamanho do alvo e centrada nele. Nenhum ser, objeto ou efeito de dano pode passar pela esfera, embora seres possam respirar normalmente dentro dela. Ao mesmo tempo o efeito é destruído ao deixar a esfera, ele deve ser aprisionado. Requer 4º círculo.',
  },

  // ── 2º CÍRCULO — MORTE ────────────────────────────────────────────────────
  {
    nome: 'Desacelerar Impacto',
    elem: 'Morte',
    circ: '2',
    exec: 'reação',
    alc: 'curto',
    dur: 'até chegar ao solo ou cena',
    pe: 3,
    desc: 'O alvo (ser ou objetos somando até 10 espaços) cai lentamente. A velocidade da queda é reduzida para 18m por rodada — o suficiente para não causar dano. Se o alvo for um projétil, o ritual faz com que ele cause metade do dano normal.',
    d_pe: '3',
    d_desc: 'Aumenta o total de alvos para seres ou objetos somando até 100 espaços.',
    v_pe: '',
    v_desc: '',
  },
  {
    nome: 'Eco Espiral',
    elem: 'Morte',
    circ: '2',
    exec: 'padrão',
    alc: 'curto',
    dur: '2 rodadas',
    pe: 3,
    desc: 'Você manifesta em suas mãos uma pequena cópia do alvo feita de cinzas. No início do próximo turno, você precisa gastar uma ação padrão para se concentrar; na rodada seguinte, descarrega a cópia, que causa dano de Morte igual ao dano que o alvo sofreu na rodada em que você se concentrou. Resistência: Fortitude reduz à metade.',
    d_pe: '3',
    d_desc: 'Muda o alvo para "até 5 seres".',
    v_pe: '7',
    v_desc: 'Muda a duração para "até 3 rodadas". Requer 4º círculo e afinidade.',
  },
  {
    nome: 'Miasma Entrópico',
    elem: 'Morte',
    circ: '2',
    exec: 'padrão',
    alc: 'médio',
    dur: 'instantânea',
    pe: 3,
    desc: 'Cria uma explosão de emanações tóxicas (nuvem com 6m de raio). Seres na área sofrem 6d8 pontos de dano químico e ficam enjoados por 1 rodada. Se passarem na resistência, sofrem metade do dano e não ficam enjoados. Resistência: Fortitude parcial (veja texto).',
    d_pe: '3',
    d_desc: 'Muda o dano para 6d8 de Morte. Requer 2º círculo.',
    v_pe: '',
    v_desc: '',
  },
  {
    nome: 'Paradoxo',
    elem: 'Morte',
    circ: '2',
    exec: 'padrão',
    alc: 'médio',
    dur: 'instantânea',
    pe: 3,
    desc: 'O ritual cria uma poderosa implosão de distorção temporal contraditória, causando 6d6 pontos de dano de Morte em todos os seres na área (esfera com 6m de raio). Resistência: Fortitude reduz à metade.',
    d_pe: '3',
    d_desc: 'Muda a área para "esfera com tamanho Médio" e a duração para cena. Em vez do normal, cria uma esfera de emanações espirais sibilantes que você pode mover 9m por rodada.',
    v_pe: '7',
    v_desc: 'Muda o dano para 13d6. Seres reduzidos a 0 PV pelo dano devem fazer um teste de Fortitude ou são reduzidos a cinzas. Requer 4º círculo.',
  },
  {
    nome: 'Velocidade Mortal',
    elem: 'Morte',
    circ: '2',
    exec: 'padrão',
    alc: 'curto',
    dur: 'sustentada',
    pe: 3,
    desc: 'Você distorce a passagem do tempo ao redor do alvo, tornando-o extremamente veloz. O alvo pode realizar uma ação de movimento adicional por turno. Esta ação não pode ser usada para conjurar rituais.',
    d_pe: '3',
    d_desc: 'Em vez de uma ação de movimento, o alvo recebe uma ação padrão adicional por turno.',
    v_pe: '7',
    v_desc: 'Muda o alvo para "alvos escolhidos". Requer 4º círculo e afinidade.',
  },

  // ── 2º CÍRCULO — SANGUE ───────────────────────────────────────────────────
  {
    nome: 'Aprimorar Físico',
    elem: 'Sangue',
    circ: '2',
    exec: 'padrão',
    alc: 'toque',
    dur: 'cena',
    pe: 2,
    desc: 'O alvo tem seus músculos tonificados e seus ligamentos reforçados, recebendo +1 em Agilidade ou Força, a escolha dele.',
    d_pe: '3',
    d_desc: 'Muda o bônus para +2. Requer 3º círculo.',
    v_pe: '7',
    v_desc: 'Muda o bônus para +3. Requer 4º círculo e afinidade.',
  },
  {
    nome: 'Descarnar',
    elem: 'Sangue',
    circ: '2',
    exec: 'padrão',
    alc: 'toque',
    dur: 'instantânea',
    pe: 3,
    desc: 'Este ritual cruel faz com que lacerações se manifestem na pele e órgãos do alvo, que sofre 6d8 pontos de dano (metade corte, metade Sangue) e fica com uma hemorragia severa. No início de cada turno, o alvo deve fazer um teste de Fortitude ou sofre 2d8 de dano de Sangue. Resistência: Fortitude parcial.',
    d_pe: '3',
    d_desc: 'Muda o dano direto para 10d8 e o dano da hemorragia para 4d8. Requer 3º círculo.',
    v_pe: '7',
    v_desc: 'Muda o alvo para você e a duração para sustentada. Enquanto o ritual durar, seus ataques corpo a corpo causam 4d8 pontos de dano de Sangue adicional e deixam o alvo com hemorragia automaticamente. Requer 3º círculo e afinidade.',
  },
  {
    nome: 'Flagelo de Sangue',
    elem: 'Sangue',
    circ: '2',
    exec: 'padrão',
    alc: 'toque',
    dur: 'cena',
    pe: 3,
    desc: 'Você toca uma pessoa, gravando uma marca escarificada no corpo dela enquanto profere uma ordem. A cada rodada que o alvo desobedecer a ordem, a marca inflige 10d6 pontos de dano de Sangue e deixa o alvo enjoado (Fortitude reduz o dano à metade e evita a condição). Resistência: Fortitude parcial.',
    d_pe: '3',
    d_desc: 'Muda o alvo para "1 ser (exceto criaturas de Sangue)". Requer 3º círculo.',
    v_pe: '7',
    v_desc: 'Como Discente, e muda a duração para "1 dia". Requer 4º círculo e afinidade.',
  },
  {
    nome: 'Hemofagia',
    elem: 'Sangue',
    circ: '2',
    exec: 'padrão',
    alc: 'toque',
    dur: 'instantânea',
    pe: 2,
    desc: 'Você arranca o sangue do corpo do alvo através de pele, causando 4d6 pontos de dano de Sangue. Resistência: nenhuma.',
    d_pe: '3',
    d_desc: 'Muda a resistência para "nenhuma". Como parte da execução do ritual, você faz um ataque corpo a corpo contra o alvo, causando 1d6+5 de dano de Sangue. Requer 2º círculo.',
    v_pe: '7',
    v_desc: 'Muda o alcance para "pessoal", para cada alvo 1 ser e causa +6 pontos de dano de Sangue. Requer 4º círculo e afinidade.',
  },
  {
    nome: 'Transfusão Vital',
    elem: 'Sangue',
    circ: '2',
    exec: 'padrão',
    alc: 'toque',
    dur: 'instantânea',
    pe: 3,
    desc: 'Você toca no alvo e transfere sua própria energia vital para ele, podendo sofrer até 30 pontos de dano de Sangue para que o alvo recupere a mesma quantidade em PV. Você não pode ficar com menos de 1 PV por causa deste ritual.',
    d_pe: '3',
    d_desc: 'Você pode transferir até 50 pontos de vida. Requer 3º círculo.',
    v_pe: '7',
    v_desc: 'Você pode transferir até 100 pontos de vida. Requer 4º círculo.',
  },

  // ── 2º CÍRCULO — MEDO ────────────────────────────────────────────────────
  {
    nome: 'Proteção contra Rituais',
    elem: 'Medo',
    circ: '2',
    exec: 'padrão',
    alc: 'toque',
    dur: 'cena',
    pe: 2,
    desc: 'Você canaliza uma aura de Medo puro, que protege o alvo contra efeitos paranormais. O alvo recebe resistência a dano paranormal 5 e +5 em testes de resistência contra rituais e habilidades de criaturas paranormais.',
    d_pe: '3',
    d_desc: 'Muda o alvo para "até 5 seres tocados". Requer 3º círculo.',
    v_pe: '6',
    v_desc: 'Muda o alvo para "até 5 seres tocados", a resistência a dano paranormal 5 e +5 em testes de resistência contra rituais e habilidades de criaturas paranormais para +10. Requer 4º círculo.',
  },
  {
    nome: 'Rejeitar Névoa',
    elem: 'Medo',
    circ: '2',
    exec: 'padrão',
    alc: 'curto',
    dur: 'cena',
    pe: 3,
    desc: 'Você manifesta um leve redemoinho de névoa (área de 6m de raio). Rituais conjurados dentro da área têm seu custo aumentado em +2 PE por círculo e sua execução aumentada em um passo.',
    d_pe: '2',
    d_desc: 'Além do normal, a DT de testes de resistência contra rituais realizados na área diminui em –5.',
    v_pe: '5',
    v_desc: 'Como discente, e o dano causado dentro da névoa por rituais é sempre mínimo.',
  },

  // ── 3º CÍRCULO — CONHECIMENTO ─────────────────────────────────────────────
  {
    nome: 'Alterar Memória',
    elem: 'Conhecimento',
    circ: '3',
    exec: 'padrão',
    alc: 'toque',
    dur: 'instantânea',
    pe: 6,
    desc: 'Você invade a mente do alvo e altera ou apaga suas memórias de até uma hora atrás. Se escolher alterar as memórias, você pode mudar detalhes de eventos recentes, mas não reescrever completamente esses eventos. O alvo recupera suas memórias após 1d4 dias. Resistência: Vontade anula.',
    d_pe: '6',
    d_desc: 'Você pode alterar memórias de até 24 horas atrás. Requer 3º círculo.',
    v_pe: '4',
    v_desc: 'Você pode alterar ou apagar permanentemente memórias de até 24 horas atrás. Requer 4º círculo.',
  },
  {
    nome: 'Contato Paranormal',
    elem: 'Conhecimento',
    circ: '3',
    exec: 'completa',
    alc: 'pessoal',
    dur: '1 dia',
    pe: 6,
    desc: 'Você barganha com a entidade de Conhecimento para que o auxilie durante o dia, em troca de se alimentar de sua Sanidade. Quando o ritual é conjurado, você recebe seis d6. Sempre que fizer um teste de perícia, você pode gastar um desses d6, rolá-lo e adicionar o resultado no teste. No entanto, sempre que rolar um 6 no dado, a entidade toma 2 pontos de Sanidade de você.',
    d_pe: '4',
    d_desc: 'Muda os dados de auxílio para d8. Sempre que rolar um 8 num desses dados, a entidade toma 3 pontos de sua Sanidade. Requer 4º círculo.',
    v_pe: '9',
    v_desc: 'Muda os dados de auxílio para d12. Sempre que rolar um 12 num desses dados, a entidade toma 5 pontos de sua Sanidade. Requer 4º círculo e afinidade.',
  },
  {
    nome: 'Mergulho Mental',
    elem: 'Conhecimento',
    circ: '3',
    exec: 'padrão',
    alc: 'toque',
    dur: 'sustentada',
    pe: 6,
    desc: 'Você mergulha nos pensamentos do alvo, para descobrir informações sobre ele. Durante o mergulho, você fica desprevenido. No início de cada turno seu, o mestre testa sua resistência ou o alvo tenta fazer um teste de Vontade. Se falhar, você responde uma pergunta que você possa responder (o que ele não sabe, não será incapaz de mentir). O que descobre depende das suas perguntas e do mestre: talvez você não descubra tudo o que há para saber, mas ganhe pistas para continuar a investigação. Resistência: Vontade parcial (veja texto).',
    d_pe: '',
    d_desc: '',
    v_pe: '4',
    v_desc: 'Muda a execução para 1 dia, o alcance para limitado e o alvo para um componente ritualístico de outra casta de magia (figura e uma máscara). Você pode realizar o mergulho mental à distância, submergindo seu rosto mascarado na água encantada mentalizada ao alvo. Requer 4º círculo.',
  },
  {
    nome: 'Vidência',
    elem: 'Conhecimento',
    circ: '3',
    exec: 'completa',
    alc: 'ilimitado',
    dur: '5 rodadas',
    pe: 6,
    desc: 'Através de uma superfície reflexiva, como um espelho, você cria uma visão de um alvo que você escolhe e seus arredores (cerca de 6m em qualquer direção). O alvo pode estar em qualquer lugar, mas tem direito a um teste de Vontade no início de cada um de seus turnos para impedir a Vidência naquele turno. Se o alvo passar em dois testes seguidos, o ritual é encerrado e o alvo fica imune a ele por uma semana. Para esse ritual funcionar, você precisa ter uma foto ou alguma coisa do alvo. Dependendo do conhecimento que você tiver dele, o alvo recebe bônus ou penalidades no seu teste de resistência: Você sabe o mínimo sobre o alvo: +10; Você possui informações sobre o alvo (idade, profissão...): +5; Você conhece bem o alvo: +0; Você tem um pertence pessoal ou roupa do alvo: -5; Você tem um parte do corpo do alvo (cabelos, unhas...): -10. Resistência: Vontade anula.',
    d_pe: '',
    d_desc: '',
    v_pe: '',
    v_desc: '',
  },

  // ── 3º CÍRCULO — ENERGIA ──────────────────────────────────────────────────
  {
    nome: 'Convocação Instantânea',
    elem: 'Energia',
    circ: '3',
    exec: 'padrão',
    alc: 'ilimitado',
    dur: 'instantânea',
    pe: 6,
    desc: 'Você invoca um objeto de qualquer lugar para sua mão. O item deve ter sido previamente preparado com o símbolo do ritual e pode ocupar no máximo 2 espaços. Se o objeto estiver sendo empunhado por outra pessoa, ela pode fazer um teste de Vontade para negar o efeito. Resistência: Vontade anula.',
    d_pe: '4',
    d_desc: 'Muda o alvo para um objeto de até 10 espaços.',
    v_pe: '9',
    v_desc: 'Muda o alvo para "1 recipiente Médio, com itens que somem até 10 espaços" e a duração para "permanente". Você encanta o recipiente para mantê-lo escondido no Outro Lado. Quando conjura esta versão do ritual, você perde 1 PE permanentemente.',
  },
  {
    nome: 'Salto Fantasma',
    elem: 'Energia',
    circ: '3',
    exec: 'padrão',
    alc: 'médio',
    dur: 'instantânea',
    pe: 6,
    desc: 'Seu corpo se transforma momentaneamente em Energia pura e viaja para outro ponto. Você não precisa perceber nem linha de efeito ao seu destino, podendo simplesmente imaginá-lo, desde que já tenha observado o local de destino (pessoalmente, por fotografia, por vídeo...). Por exemplo, pode se transportar 3m além para ultrapassar uma porta fechada. Uma vez transportado, você não pode agir até o resto do seu turno. Este ritual não permite que você apareça dentro de um corpo sólido; se o ponto de chegada não tem espaço livre, você ressurge na área vazia mais próxima.',
    d_pe: '2',
    d_desc: 'Muda a execução para reação (1,5m), recebendo +10 na Defesa e em testes de Reflexos contra um ataque ou efeito que esteja atingindo-o. Requer 2º círculo.',
    v_pe: '6',
    v_desc: 'Muda o alcance para longo e o alvo para você e dois outros seres voluntários que você esteja tocando. Requer 4º círculo.',
  },
  {
    nome: 'Transfigurar Água',
    elem: 'Energia',
    circ: '3',
    exec: 'padrão',
    alc: 'longo',
    dur: 'cena',
    pe: 6,
    desc: 'Você canaliza energia sobre um corpo de água. Ao conjurar o ritual, escolha um dos seguintes efeitos: Congelar, Derreter, Encher ou Evaporar. Área: esfera com 30m de raio.',
    d_pe: '',
    d_desc: '',
    v_pe: '5',
    v_desc: 'Aumenta o deslocamento dos alvos em +12m e o de evaporar para 10d8.',
  },
  {
    nome: 'Transfigurar Terra',
    elem: 'Energia',
    circ: '3',
    exec: 'padrão',
    alc: 'longo',
    dur: 'instantânea',
    pe: 6,
    desc: 'Você imbui terra, pedra, lama, argila ou areia na área com Energia. Ao conjurar o ritual, escolha um dos seguintes efeitos: Amolecer, Modelar ou Solidificar. Área: terra, com 1,5m de lado.',
    d_pe: '3',
    d_desc: 'Muda a área para 15 cubos com 1,5m de lado. Requer 3º círculo.',
    v_pe: '7',
    v_desc: 'Também afeta todos os tipos de minerais e metais. Requer 4º círculo.',
  },

  // ── 3º CÍRCULO — MORTE ────────────────────────────────────────────────────
  {
    nome: 'Âncora Temporal',
    elem: 'Morte',
    circ: '3',
    exec: 'padrão',
    alc: 'curto',
    dur: 'cena',
    pe: 6,
    desc: 'Uma aura espiralada surge sobre o alvo. No início de cada turno dele, ele deve fazer um teste de Vontade. Se falhar, não poderá se deslocar naquele turno (ainda pode agir). Se o alvo passar nesse teste dois turnos seguidos, o efeito termina. Resistência: Vontade parcial.',
    d_pe: '',
    d_desc: '',
    v_pe: '4',
    v_desc: 'Muda o alvo para "seres à sua escolha". Requer 4º círculo.',
  },
  {
    nome: 'Poeira da Podridão',
    elem: 'Morte',
    circ: '3',
    exec: 'padrão',
    alc: 'médio',
    dur: 'sustentada',
    pe: 6,
    desc: 'Você manifesta uma nuvem de poeira que apodrece os seres na área (6m de raio). Ao conjurar o ritual e no início de cada turno, seres e objetos na área sofrem 4d8 pontos de dano de Morte (Fortitude reduz à metade). Alvos que falharem também não podem recuperar PV de nenhuma forma por uma rodada.',
    d_pe: '',
    d_desc: '',
    v_pe: '4',
    v_desc: 'Muda o dano para 4d8+16.',
  },
  {
    nome: 'Tentáculos de Lodo',
    elem: 'Morte',
    circ: '3',
    exec: 'padrão',
    alc: 'médio',
    dur: 'cena',
    pe: 6,
    desc: 'Uma fenda sombria se abre no chão, de onde surgem tentáculos feitos de lodo da Morte (círculo com 6m de raio). Ao conjurar o ritual e no início de cada turno, você faz um teste de agarrar (usando Ocultismo em vez de Luta) contra cada alvo na área. Se vencer, o ser é agarrado; se já estava agarrado, sofre 4d6 pontos de dano. Os tentáculos são imunes a dano.',
    d_pe: '',
    d_desc: '',
    v_pe: '5',
    v_desc: 'Aumenta o raio da área para 9m e aumenta o dano dos tentáculos para 6d6.',
  },
  {
    nome: 'Zerar Entropia',
    elem: 'Morte',
    circ: '3',
    exec: 'padrão',
    alc: 'curto',
    dur: 'cena',
    pe: 6,
    desc: 'Você zera completamente a entropia do alvo em relação ao ambiente, deixando-o paralisado. Se passar na resistência (Vontade), em vez disso fica lento. No início de cada um de seus turnos, o alvo deve fazer um teste de Vontade. Se passar, encerra o efeito. Resistência: Vontade parcial.',
    d_pe: '4',
    d_desc: 'Muda o alvo para "1 ser". Requer 4º círculo.',
    v_pe: '11',
    v_desc: 'Muda o alvo para "seres escolhidos". Requer 4º círculo e afinidade.',
  },

  // ── 3º CÍRCULO — SANGUE ───────────────────────────────────────────────────
  {
    nome: 'Ferver Sangue',
    elem: 'Sangue',
    circ: '3',
    exec: 'padrão',
    alc: 'curto',
    dur: 'sustentada',
    pe: 6,
    desc: 'O sangue do alvo aquece até entrar em ebulição. Quando o ritual é conjurado, e no início de cada turno do alvo, ele deve fazer um teste de Fortitude. Se falhar, sofre 4d8 pontos de dano de Sangue e fica fraco; se passar, sofre metade do dano. Se o alvo passar nesse teste dois turnos seguidos, o efeito termina. Resistência: Fortitude parcial.',
    d_pe: '',
    d_desc: '',
    v_pe: '4',
    v_desc: 'Muda o alvo para "seres escolhidos". Requer 4º círculo e afinidade.',
  },
  {
    nome: 'Forma Monstruosa',
    elem: 'Sangue',
    circ: '1',
    exec: 'padrão',
    alc: 'pessoal',
    dur: 'cena',
    pe: 1,
    desc: 'Seu corpo se transforma, assumindo uma forma que combina suas características com as de uma criatura de Sangue; suas roupas e proteção se mesclam à sua carne, transformando-se em uma couraça, e quaisquer objetos em suas mãos se fundem aos seus braços, transformando-se em garras pontiagudas. Seu equipamento fica inacessível, mas seus bônus são mantidos. Seu tamanho muda para Grande e você recebe +5 em testes de ataque e +5 em testes de dano contra o corpo e +30 PV temporários. Sua mente é tomada por fúria selvagem: você não pode falar nem comunicar-se e cada rodada você deve atacar o ser mais próximo possível. Se não houver um ser por perto, você deve se deslocar em direção ao ser mais próximo de você.',
    d_pe: '3',
    d_desc: 'Muda a resistência para "nenhuma". Como parte da execução do ritual, você faz um ataque corpo a corpo contra o alvo, causando 1d6+5 de dano de Sangue. Requer 2º círculo.',
    v_pe: '7',
    v_desc: 'Muda o alcance para "pessoal", para cada alvo 1 ser e causa +6 pontos de dano de Sangue adicionais. Requer 4º círculo e afinidade.',
  },
  {
    nome: 'Purgatório',
    elem: 'Sangue',
    circ: '3',
    exec: 'padrão',
    alc: 'curto',
    dur: 'sustentada',
    pe: 6,
    desc: 'Você faz brotar uma poça de sangue pegajoso na área afetada (6m de raio). Inimigos na área se tornam vulneráveis a dano balístico, de corte, de impacto e de perfuração. Um alvo que tente sair da área sofre 6d6 de dano de Sangue e deve fazer um teste de Fortitude. Se falhar, não consegue se mover e perde a ação de movimento. Resistência: Fortitude parcial.',
    d_pe: '',
    d_desc: '',
    v_pe: '',
    v_desc: '',
  },
  {
    nome: 'Vomitar Pestes',
    elem: 'Sangue',
    circ: '3',
    exec: 'padrão',
    alc: 'médio',
    dur: 'sustentada',
    pe: 6,
    desc: 'Você vomita um enxame Grande de pequenas criaturas de Sangue. No final de cada turno, o enxame causa 5d12 pontos de dano de Sangue a qualquer ser no espaço dele (Reflexos reduz à metade). Você pode gastar uma ação de movimento para mover o enxame com deslocamento de 12m.',
    d_pe: '2',
    d_desc: 'Além do normal, um alvo que falhe no teste de Reflexos fica agarrado (o enxame escala e cobre o corpo dele).',
    v_pe: '5',
    v_desc: 'O enxame vira Enorme (cubo de 6m de lado) e ganha deslocamento de voo 18m.',
  },

  // ── 3º CÍRCULO — MEDO ────────────────────────────────────────────────────
  {
    nome: 'Dissipar Ritual',
    elem: 'Medo',
    circ: '3',
    exec: 'padrão',
    alc: 'médio',
    dur: 'instantânea',
    pe: 6,
    desc: 'Você dissipa rituais ativos, como se a duração deles tivesse acabado. Efeitos de rituais instantâneos não podem ser dissipados. Faça um teste de Ocultismo; você anula quaisquer rituais ativos no alvo ou na área com DT igual ou menor que o resultado do teste.',
    d_pe: '',
    d_desc: '',
    v_pe: '',
    v_desc: '',
  },

  // ── 4º CÍRCULO — CONHECIMENTO ─────────────────────────────────────────────
  {
    nome: 'Controle Mental',
    elem: 'Conhecimento',
    circ: '4',
    exec: 'padrão',
    alc: 'médio',
    dur: 'sustentada',
    pe: 10,
    desc: 'Você domina a mente do alvo, obedecendo todos os seus comandos, exceto ordens suicidas. A cada um de seus turnos, Um alvo pode resistir a um teste de Vontade no final de cada um de seus turnos para se livrar do efeito. Alvos que passarem no teste ficam pasmos por 1 rodada. Resistência: Vontade parcial.',
    d_pe: '5',
    d_desc: 'Muda o alvo para até cinco pessoas ou animais. Requer afinidade com Conhecimento.',
    v_pe: '10',
    v_desc: 'Muda o alvo para até dez pessoas ou animais. Requer afinidade com Conhecimento.',
  },
  {
    nome: 'Inexistir',
    elem: 'Conhecimento',
    circ: '4',
    exec: 'padrão',
    alc: 'toque',
    dur: 'instantânea',
    pe: 10,
    desc: 'Você toca o alvo com a intenção de apagá-lo completamente da existência, causando 10d12+10 pontos de dano de Conhecimento. Se o alvo passar no teste de resistência, em vez disso sofre 2d12 pontos de dano e fica debilitado por uma rodada. Se os PV do alvo forem reduzidos a 0, ele será completamente apagado da existência. Resistência: Vontade parcial.',
    d_pe: '5',
    d_desc: 'Muda o dano para 15d12+15 e o dano resistido para 3d12.',
    v_pe: '10',
    v_desc: 'Muda o dano para 20d12+20 e o dano resistido para 4d12. Requer afinidade.',
  },
  {
    nome: 'Possessão',
    elem: 'Conhecimento',
    circ: '4',
    exec: 'padrão',
    alc: 'longo',
    dur: '1 dia',
    pe: 10,
    desc: 'Você projeta sua consciência no corpo de uma pessoa viva ou morta. Enquanto possuir o alvo, você assume o controle total do corpo dele e usa os atributos físicos do alvo. Retornar para o seu corpo voluntariamente é uma ação livre. Resistência: Vontade anula.',
    d_pe: '',
    d_desc: '',
    v_pe: '',
    v_desc: '',
  },

  // ── 4º CÍRCULO — ENERGIA ──────────────────────────────────────────────────
  {
    nome: 'Alterar Destino',
    elem: 'Energia',
    circ: '4',
    exec: 'reação',
    alc: 'pessoal',
    dur: 'instantânea',
    pe: 10,
    desc: 'Quando sofrer este ritual, escolha um elemento entre as possibilidades e escolhendo o melhor. Você recebe +15 em um teste de resistência ou na Defesa contra um ataque.',
    d_pe: '',
    d_desc: '',
    v_pe: '5',
    v_desc: 'Muda o alcance para "curto" e o alvo para "um aliado à sua escolha".',
  },
  {
    nome: 'Deflagração de Energia',
    elem: 'Energia',
    circ: '4',
    exec: 'completa',
    alc: 'pessoal',
    dur: 'instantânea',
    pe: 10,
    desc: 'Você acumula uma quantidade imensa de Energia, então a libera em uma explosão intensa (explosão de 15m de raio). Todos na área sofrem 3d10 x 10 pontos de dano de Energia e todos os itens tecnológicos (armas de fogo, acessórios e utensílios) param de funcionar. Você não é afetado. Resistência: Fortitude parcial.',
    d_pe: '',
    d_desc: '',
    v_pe: '5',
    v_desc: 'Afeta apenas alvos a sua escolha.',
  },
  {
    nome: 'Teletransporte',
    elem: 'Energia',
    circ: '4',
    exec: 'padrão',
    alc: 'toque',
    dur: 'instantânea',
    pe: 10,
    desc: 'O ritual transforma o corpo e equipamento dos alvos em energia e os faz reaparecer num lugar da sua escolha a até 1.000km. Quando conjura este ritual, você precisa fazer um teste de Ocultismo, com DT 17. Um lugar que você visitou com frequência. DT 20. Um lugar que você visitou com frequência. DT 25. Um lugar que você já visitou por menos de 1 vez. DT 35. Um lugar que você nunca visitou e só conhece a partir da descrição de outra pessoa para esse lugar.',
    d_pe: '',
    d_desc: '',
    v_pe: '5',
    v_desc: 'Pode se teletransportar para qualquer local na Terra.',
  },

  // ── 4º CÍRCULO — MORTE ────────────────────────────────────────────────────
  {
    nome: 'Convocar o Algoz',
    elem: 'Morte',
    circ: '4',
    exec: 'padrão',
    alc: '1,5m',
    dur: 'sustentada',
    pe: 4,
    desc: 'Usando os medos subconscientes do alvo você manipula uma espiral da Morte para criar uma imagem do algoz que ele mais teme. Apenas a própria visão do algoz com nitidez, outros seres presentes (incluindo você) enxergam apenas um vulto sombrio. O algoz surge a 12m em direção à vítima. Se o algoz terminar o turno em alcance curto da vítima, ele deve fazer um teste de Vontade; se falhar, fica abalada. Se o algoz terminar o turno em alcance curto da vítima, ele deve fazer um teste de Fortitude. Se não passar, sofre 6d6 pontos de dano de Morte (o alvo sofre o dobro). Se passar, sofre 6d6 pontos de dano de Morte e o algoz desaparece ao deixar um alvo sem dano ou se dissipado. Resistência: Vontade parcial, Fortitude parcial.',
    d_pe: '',
    d_desc: '',
    v_pe: '',
    v_desc: '',
  },
  {
    nome: 'Distorção Temporal',
    elem: 'Morte',
    circ: '4',
    exec: 'padrão',
    alc: 'pessoal',
    dur: '3 rodadas',
    pe: 10,
    desc: 'Este ritual distorce o fluxo de tempo em relação a você, criando um pequeno bolsão temporal que dura 3 rodadas. Durante este tempo, você pode agir, mas não pode se deslocar do lugar nem interagir com seres e objetos. Da mesma forma, efeitos contínuos não o afetam.',
    d_pe: '',
    d_desc: '',
    v_pe: '',
    v_desc: '',
  },
  {
    nome: 'Fim Inevitável',
    elem: 'Morte',
    circ: '4',
    exec: 'completa',
    alc: 'extremo',
    dur: '4 rodadas',
    pe: 10,
    desc: 'Você cria um vácuo em um espaço desocupado a sua escolha. No início de cada turno, todos os seres a até 90m do vácuo devem fazer um teste de Fortitude. Em caso de falha, ficam caídos e são puxados 30m na direção do vácuo. Seres e objetos que iniciem seu turno tocando o vácuo sofrem 100 pontos de dano de Morte por rodada.',
    d_pe: '5',
    d_desc: 'Muda a duração para "5 rodadas" e o efeito para que você não seja afetado. Requer afinidade.',
    v_pe: '10',
    v_desc: 'Muda a duração para "6 rodadas" e o efeito para que seres escolhidos dentro do alcance não sejam afetados. Requer afinidade.',
  },

  // ── 4º CÍRCULO — SANGUE ───────────────────────────────────────────────────
  {
    nome: 'Capturar o Coração',
    elem: 'Sangue',
    circ: '4',
    exec: 'padrão',
    alc: 'curto',
    dur: 'cena',
    pe: 10,
    desc: 'Você desperta uma paixão doentia e obcecada por você no alvo, que passa a querer agradá-lo a todo custo. No início de cada turno do alvo, ele deve fazer um teste de Vontade. Se falhar, age de forma a ajudá-lo. Se o alvo passar nesse teste dois turnos seguidos, o efeito termina. Resistência: Vontade parcial.',
    d_pe: '',
    d_desc: '',
    v_pe: '',
    v_desc: '',
  },
  {
    nome: 'Invólucro de Carne',
    elem: 'Sangue',
    circ: '4',
    exec: 'padrão',
    alc: 'curto',
    dur: 'cena',
    pe: 10,
    desc: 'Você manifesta uma poça de sangue no chão, de onde emerge uma cópia exata sua. Ela é idêntica em aparência e capacidades (em termos de jogo, tem as mesmas estatísticas) e surge com uma cópia das todas as memórias mundanas que você possui até esse momento. A cópia não tem consciência (valor de Intelecto e Presença nulos) e não age senão que for de uma ordem. Você pode gastar uma ação de movimento para dar uma ordem à cópia, como "ataque aquele inimigo". No final de cada um de seus turnos, a cópia segue a ordem da melhor maneira possível, mas ainda é incapaz de tomar decisões sutis e aceitar qualquer ordem perigosa ao hesitar, mesmo que leve à sua destrução. Alternativamente, no início de seu turno, você pode controlar diretamente a cópia. Se fizer isso, você não pode transar temporário a cópia e assume o controle dela. Qualquer ser que interagir com a cópia trata direto com um teste de Percepção (DT do ritual) para perceber que se trata de uma cópia. A cópia se desfaz ao sofrer qualquer ponto de dano de Sangue ou sair do alcance.',
    d_pe: '',
    d_desc: '',
    v_pe: '',
    v_desc: '',
  },
  {
    nome: 'Vínculo de Sangue',
    elem: 'Sangue',
    circ: '4',
    exec: 'padrão',
    alc: 'curto',
    dur: 'cena',
    pe: 10,
    desc: 'Você manifesta um símbolo de Sangue no seu corpo e no corpo do alvo. Sempre que você sofrer dano, o alvo deve fazer um teste de Fortitude. Se ele falhar, você sofre apenas metade do dano e ele sofre a metade restante. Você pode conjurar o ritual com efeito inverso. Resistência: Fortitude anula.',
    d_pe: '',
    d_desc: '',
    v_pe: '',
    v_desc: '',
  },

  // ── 4º CÍRCULO — MEDO ────────────────────────────────────────────────────
  {
    nome: 'Canalizar o Medo',
    elem: 'Medo',
    circ: '4',
    exec: 'padrão',
    alc: 'toque',
    dur: 'permanente até ser descarregada',
    pe: 10,
    desc: 'Você transfere parte de seu poder para outra pessoa. Escolha um ritual de até 3º círculo que você conheça; o alvo pode conjurar este ritual em sua forma básica uma vez, sem pagar seu custo em PE. Até o ritual transferido ser conjurado, seus PE máximos diminuem em um valor igual ao custo dele.',
    d_pe: '',
    d_desc: '',
    v_pe: '',
    v_desc: '',
  },
  {
    nome: 'Conhecendo o Medo',
    elem: 'Medo',
    circ: '4',
    exec: 'padrão',
    alc: 'toque',
    dur: 'cena',
    pe: 10,
    desc: 'Você manifesta medo absoluto na mente do alvo. Se ele falhar no teste de resistência, a Sanidade dele é reduzida a 0 e ele fica enlouquecendo. Se ele passar, sofre 10d6 pontos de dano mental e fica apavorado por 1 rodada. Uma pessoa que fique insana pelo efeito deste ritual se transforma em uma criatura paranormal. Resistência: Vontade parcial.',
    d_pe: '',
    d_desc: '',
    v_pe: '',
    v_desc: '',
  },
  {
    nome: 'Lâmina do Medo',
    elem: 'Medo',
    circ: '4',
    exec: 'padrão',
    alc: 'toque',
    dur: 'instantânea',
    pe: 10,
    desc: 'Você manifesta uma lâmina impossível. Se o alvo falhar no teste de Fortitude, seus PV são reduzidos a 0 e ele fica morrendo. Se passar, sofre 10d8 pontos de dano de Medo (ignora todas as resistências) e fica apavorado por 1 rodada. Resistência: Fortitude parcial.',
    d_pe: '',
    d_desc: '',
    v_pe: '',
    v_desc: '',
  },
  {
    nome: 'Medo Tangível',
    elem: 'Medo',
    circ: '4',
    exec: 'padrão',
    alc: 'pessoal',
    dur: 'cena',
    pe: 10,
    desc: 'O ritual transforma seu corpo em uma manifestação do Medo, tornando-o imune a efeitos mundanos. Você fica imune às condições atordoado, cego, debilitado, enjoado, envenenado, exausto, fatigado, fraco, lento e paralisado.',
    d_pe: '',
    d_desc: '',
    v_pe: '',
    v_desc: '',
  },
  {
    nome: 'Presença do Medo',
    elem: 'Medo',
    circ: '4',
    exec: 'padrão',
    alc: 'pessoal',
    dur: 'sustentada',
    pe: 10,
    desc: 'Você se torna um receptáculo para o Medo puro, emanando ondas de pavor e ruína (emanação de 9m de raio). Alvos dentro da área sofrem 5d8 de dano mental e 5d8 de dano de Medo (Vontade reduz ambos à metade). Alvos que falharem ficam atordoados por uma rodada (este efeito funciona apenas uma vez por cena).',
    d_pe: '',
    d_desc: '',
    v_pe: '',
    v_desc: '',
  },
];